### ISSUE TITLE
Bug in copy assignments

### ISSUE THREAD

**Issue by magnatelee** [zdevito/terra#372]
Current status:

 - [X] (pass in master) `tests/bug372.t`
 - [X] (pass in master) `tests/bug372b.t`
 - [X] (pass  in #391) `tests/bug372c.t` ([gist](https://gist.github.com/elliottslaughter/321fd0969aaabb5e47f8434e0a533525))
 - [X] (pass in #391) `tests/bug372d.t` ([gist](https://gist.github.com/elliottslaughter/e7adba28de2dbc43378de1fdba9766d6))
 - [X] (fast in #391) `tests/bug372_perf.t` ([gist](https://gist.github.com/elliottslaughter/b1f9e22af7d9deedcc02a2b6161c700d))

Original reproducer:

schema.h
```
#ifndef __SCHEMA_H__
#define __SCHEMA_H__

struct Config {
  union  {
    char FileDir[16];
    struct  {
      unsigned int length;
      double values;
    } s;
  } u;
};

#endif // __SCHEMA_H__
```

reproducer.t
```
local C = terralib.includec("stdio.h")
local SCHEMA = terralib.includec("schema.h")

terra main()
  var config : SCHEMA.Config
  C.snprintf(&(config.u.FileDir[0]), 16, "%s", "String111222333")
  C.printf("orig: %s\n", config.u.FileDir)
  var copy = config
  C.printf("copy: %s\n", copy.u.FileDir)
end

main()
```

This code prints out the following (the exact output might be different on different platforms):
```
orig: String111222333
copy: Stri
```
However, the output should have been this:
```
orig: String111222333
copy: String111222333
```
If I change the type of `length` to any 8-byte type, the code produces a correct output.

I suspect Terra doesn't emit correct copy assignment code when the fields of a union are not aligned.

**Comment by magnatelee** [comment]
In fact, this bug is reproduced purely in Terra. Here is a even simpler reproducer:

```
local C = terralib.includec("stdio.h")

struct st
{
  length : uint;
  values : double;
}

struct Config
{
  union {
    FileDir : int8[16],
    s : st,
  }
}

terra main()
  var config : Config
  C.snprintf(&(config.FileDir[0]), 16, "%s", "String111222333")
  C.printf("orig: %s\n", config.FileDir)
  var copy = config
  C.printf("copy: %s\n", copy.FileDir)
end

main()
```

**Comment by aiverson** [comment]
I can reproduce this on my system.

**Comment by manopapad** [comment]
Some more info on this. If you do:
```
terra main()
  var config : Config
  var copy = config
end
main:setoptimized(false)
main:disas()
```

you get:

```
definition 	{} -> {}

; Function Attrs: noinline optnone
define void @"$main"() #0 {
entry:
  %copy = alloca %0
  %config = alloca %0
  %0 = load %0* %config
  store %0 %0, %0* %copy
  ret void
}

assembly for function at address 0x7fa067cf8010
0x7fa067cf8010(+0):		mov	eax, dword ptr [rsp - 32]
0x7fa067cf8014(+4):		vmovsd	xmm0, qword ptr [rsp - 24]
0x7fa067cf801a(+10):		vmovsd	qword ptr [rsp - 8], xmm0
0x7fa067cf8020(+16):		mov	dword ptr [rsp - 16], eax
0x7fa067cf8024(+20):		ret
```

The x86 assembly seems to suggest that the first case of the union is ignored, and instead the copying is decomposed into a copy of the 4 bytes in positions 0..3 (the uint), followed by a copy of the 8 bytes in positions 8..15 (the double), with bytes 4..7 of the target left unfilled. I don't know enough of LLVM IR to know if this is what the following commands are supposed to do (which means that Terra is not emitting the correct commands):

```
  %0 = load %0* %config
  store %0 %0, %0* %copy
```

or that LLVM has a bug.

For reference, here is what pure clang 3.5 produces for the equivalent C program:

```
struct st {
  unsigned int length;
  double values;
};
struct Config {
  union {
    char FileDir[16];
    struct st s;
  } u;
};
int main() {
  struct Config config;
  config.u.FileDir[0] = 42;
  struct Config copy;
  copy = config;
}
```

```
%struct.Config = type { %union.anon }
%union.anon = type { %struct.st }
%struct.st = type { i32, double }

; Function Attrs: nounwind uwtable
define i32 @main() #0 {
  %config = alloca %struct.Config, align 8
  %copy = alloca %struct.Config, align 8
  %1 = bitcast %struct.Config* %copy to i8*
  %2 = bitcast %struct.Config* %config to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %1, i8* %2, i64 16, i32 8, i1 false)
  ret i32 0
}
```

I.e. clang doesn't bother with copying field-by-field, and just emits `memcpy`. Interestingly, it also seems to drop `FileDir` from the struct definition (unless you grow it to be larger than `struct st`, in which case it just pads the struct with enough bytes to cover the string, which is safe to do, since it just uses `memcpy` for copying anyway).

**Comment by manopapad** [comment]
I believe the best way to fix this is to change the code generation for assignment statements:
https://github.com/zdevito/terra/blob/ed050f69632a3cce3b4cdaadfe070cdc02932515/src/tcompiler.cpp#L2630-L2652
to use `memcpy` in the case of structs.

**Comment by elliottslaughter** [comment]
Fixed by #378

**Comment by elliottslaughter** [comment]
Actually, this is still broken in the original case, it seems that C headers must be going down a different code path.

Reproducer:

```
local C = terralib.includec("stdio.h")
local S = terralib.includecstring [[
#ifndef __SCHEMA_H__
#define __SCHEMA_H__

struct Config {
  union  {
    char FileDir[16];
    struct  {
      unsigned int length;
      double values;
    } s;
  } u;
};

#endif // __SCHEMA_H__
]]

terra main()
  var config : S.Config
  C.snprintf(&(config.u.FileDir[0]), 16, "%s", "String111222333")
  C.printf("orig: %s\n", config.u.FileDir)
  var copy = config
  C.printf("copy: %s\n", copy.u.FileDir)
end

main()
```

**Comment by manopapad** [comment]
#378 also seems to change how Terra interfaces with C when using unions. The example in this reproducer [regression372.tar.gz](https://github.com/zdevito/terra/files/3336162/regression372.tar.gz) used to work before this commit.

**Comment by elliottslaughter** [comment]
I reverted #378 for now until we can find a fix that doesn't cause regressions.

**Comment by elliottslaughter** [comment]
A new patch is available at #381. @magnatelee @manopapad Please test your full codes against this.

**Comment by elliottslaughter** [comment]
Unfortunately we keep seeming to hit corner cases with this. Here's another example that's misbehaving:

https://gist.github.com/elliottslaughter/321fd0969aaabb5e47f8434e0a533525

**Comment by elliottslaughter** [comment]
We're seeing a performance regression in master (4eafb183a71280b430996f4aa0b60f87a0561557) that occurs when you try to perform certain operations with large structs. The reproducer takes a very long time to compile (as in, tens of minutes). If you uncomment the two flags at the bottom, you can see why: the one `llvm.memcpy` intrinsic is generating thousands of lines of assembly. Clearly we're still doing something wrong.

https://gist.github.com/elliottslaughter/b1f9e22af7d9deedcc02a2b6161c700d

**Comment by elliottslaughter** [comment]
Yet another corner case, this time with attrload/attrstore:

https://gist.github.com/elliottslaughter/e7adba28de2dbc43378de1fdba9766d6

**Comment by elliottslaughter** [comment]
All the outstanding reproducers are now fixed, at least for the moment. Going to keep this issue open for a bit longer to confirm with other codes.

**Comment by elliottslaughter** [comment]
Confirmed fixed in the original code. Closing (and hope it stays closed this time).
